In [1]:
from pathlib import Path
import sys

root_path = next((p for p in [Path.cwd(), *Path.cwd().parents] if (p / "utils").exists()), None)
if root_path is None:
    raise FileNotFoundError("Could not locate project root containing 'utils' directory")
sys.path.append(str(root_path))

from utils.helpers import load_data, save_excel_file
from utils.CBM_score_per_task import CBM_score_per_task_exam

In [2]:
df = load_data("../data/CBM_format/IN1020_2025_CBM.csv")
df = df[['student_id', 'question_number', 'answer_alternative', 'confidence_level', 'auto_score', 'total_score']]
df.head()

Data loaded successfully from ../data/CBM_format/IN1020_2025_CBM.csv

,student_id,question_number,answer_alternative,confidence_level,auto_score,total_score
0,363,2.1,5,50.0,14.0,53.82
1,363,2.1,2,25.0,14.0,53.82
2,363,2.1,4,25.0,14.0,53.82
3,363,2.1,3,0.0,14.0,53.82
4,363,2.1,1,0.0,14.0,53.82

In [3]:
result2_1 = CBM_score_per_task_exam(df, question_number='2.1', map_answers=['F', 'R', 'P', 'M', 'P'])
#rename column score to score_2_1
result2_1 = result2_1.rename(columns={"score": "score_2_1"})
result2_1.head()

   student_id  score_2_1
0           1          7
1           2          8
2           3          6
3           4          8
4           5          5

In [4]:
result2_2 = CBM_score_per_task_exam(df, question_number='2.2', map_answers=['M', 'R', 'M', 'P', 'F'])
#rename column score to score_2_2
result2_2 = result2_2.rename(columns={"score": "score_2_2"})
result2_2.head()

   student_id  score_2_2
0           1          3
1           2          8
2           3          8
3           4          8
4           5         -2

In [5]:
result2_3 = CBM_score_per_task_exam(df, question_number='2.3', map_answers=['R', 'P', 'M', 'F', 'M'])
#rename column score to score_2_3
result2_3 = result2_3.rename(columns={"score": "score_2_3"})
result2_3.head()

   student_id  score_2_3
0           1          3
1           2         -2
2           3          0
3           4          7
4           5         -1

In [6]:
result2_4 = CBM_score_per_task_exam(df, question_number='2.4', map_answers=['R', 'P', 'M', 'F', 'F'])
#rename column score to score_2_4
result2_4 = result2_4.rename(columns={"score": "score_2_4"})
result2_4.head()

   student_id  score_2_4
0           1        -12
1           2          8
2           3        -12
3           4          8
4           5         -3

In [7]:
result2_5 = CBM_score_per_task_exam(df, question_number='2.5', map_answers=['P', 'M', 'R', 'F', 'P'])
#rename column score to score_2_5
result2_5 = result2_5.rename(columns={"score": "score_2_5"})
result2_5.head()

   student_id  score_2_5
0           1          8
1           2          8
2           3        -16
3           4         -3
4           5          8

In [8]:
result2_6 = CBM_score_per_task_exam(df, question_number='2.6', map_answers=['P', 'M', 'P', 'R', 'F'])
#rename column score to score_2_6
result2_6 = result2_6.rename(columns={"score": "score_2_6"})
result2_6.head()

   student_id  score_2_6
0           1         -4
1           2          8
2           3          6
3           4          8
4           5          5

In [9]:
result2_7 = CBM_score_per_task_exam(df, question_number='2.7', map_answers=['P', 'R', 'M', 'P', 'F'])
#rename column score to score_2_7
result2_7 = result2_7.rename(columns={"score": "score_2_7"})
result2_7.head()

   student_id  score_2_7
0           1          6
1           2         -2
2           3         -2
3           4          8
4           5          6

In [10]:
#Create a table with all the scores for each question, merge on student_id
overview_table = result2_1.merge(result2_2, on='student_id', how='outer') \
    .merge(result2_3, on='student_id', how='outer') \
    .merge(result2_4, on='student_id', how='outer') \
    .merge(result2_5, on='student_id', how='outer') \
    .merge(result2_6, on='student_id', how='outer') \
    .merge(result2_7, on='student_id', how='outer')
#Add new column with the total score for each student
overview_table['total_CBM_score'] = overview_table[['score_2_1', 'score_2_2', 'score_2_3', 'score_2_4', 'score_2_5', 'score_2_6', 'score_2_7']].sum(axis=1)
# Add 'invalid_answer' in cells where score is NaN
overview_table = overview_table.fillna('invalid_answer')
overview_table.head()

,student_id,score_2_1,score_2_2,score_2_3,score_2_4,score_2_5,score_2_6,score_2_7,total_CBM_score
0,1,7.0,3.0,3.0,-12.0,8.0,-4.0,6.0,11.0
1,2,8.0,8.0,-2.0,8.0,8.0,8.0,-2.0,36.0
2,3,6.0,8.0,0.0,-12.0,-16.0,6.0,-2.0,-10.0
3,4,8.0,8.0,7.0,8.0,-3.0,8.0,8.0,44.0
4,5,5.0,-2.0,-1.0,-3.0,8.0,5.0,6.0,18.0

In [11]:
output_folder = root_path / "analysis" / "CBM" / "2025" / "Exam" / "data" / "CBM_format"
save_excel_file(overview_table, "IN1020_2025_CBM_exam_results", output_folder)

✅ DataFrame saved as: /Users/yulis/Desktop/Masteroppgave_Eksamensanalyse/analysis/CBM/2025/Exam/data/CBM_format/IN1020_2025_CBM_exam_results.xlsx