In [4]:
from pathlib import Path
import sys

root_path = next((p for p in [Path.cwd(), *Path.cwd().parents] if (p / "utils").exists()), None)
if root_path is None:
    raise FileNotFoundError("Could not locate project root containing 'utils' directory")
sys.path.append(str(root_path))

from utils.helpers import load_data, save_excel_file
from utils.CBM_score_per_task import CBM_score_per_task_exam, CBM_score_per_task_exam_no_minus_points

In [5]:
df = load_data("../data/CBM_format/IN1020_2025_CBM.csv")
df = df[['student_id', 'question_number', 'auto_score_per_question', 'answer_alternative', 'confidence_level', 'auto_score', 'total_score']]
df['total_score'] = df['total_score']-df['auto_score']
df.sort_values(by=['student_id', 'question_number', 'answer_alternative'], inplace=True)
df.head()

Data loaded successfully from ../data/CBM_format/IN1020_2025_CBM.csv

,student_id,question_number,auto_score_per_question,answer_alternative,confidence_level,auto_score,total_score
10157,1,2.1,2.0,1,0.0,14.0,30.01
10160,1,2.1,2.0,2,75.0,14.0,30.01
10156,1,2.1,2.0,3,0.0,14.0,30.01
10158,1,2.1,2.0,4,0.0,14.0,30.01
10159,1,2.1,2.0,5,25.0,14.0,30.01

### With minus points

In [6]:
result2_1 = CBM_score_per_task_exam(df, question_number='2.1', map_answers=['F', 'R', 'P', 'M', 'P'])
#rename column score to score_2_1
result2_1 = result2_1.rename(columns={"score": "score_2_1"})
result2_1.head()

   student_id  score_2_1
0           1          7
1           2          8
2           3          6
3           4          8
4           5          5

In [7]:
result2_2 = CBM_score_per_task_exam(df, question_number='2.2', map_answers=['M', 'R', 'M', 'P', 'F'])
#rename column score to score_2_2
result2_2 = result2_2.rename(columns={"score": "score_2_2"})
result2_2.head()

   student_id  score_2_2
0           1          3
1           2          8
2           3          8
3           4          8
4           5         -2

In [8]:
result2_3 = CBM_score_per_task_exam(df, question_number='2.3', map_answers=['R', 'P', 'M', 'F', 'M'])
#rename column score to score_2_3
result2_3 = result2_3.rename(columns={"score": "score_2_3"})
result2_3.head()

   student_id  score_2_3
0           1          3
1           2         -2
2           3          0
3           4          7
4           5         -1

In [9]:
result2_4 = CBM_score_per_task_exam(df, question_number='2.4', map_answers=['R', 'P', 'M', 'F', 'F'])
#rename column score to score_2_4
result2_4 = result2_4.rename(columns={"score": "score_2_4"})
result2_4.head()

   student_id  score_2_4
0           1        -12
1           2          8
2           3        -12
3           4          8
4           5         -3

In [10]:
result2_5 = CBM_score_per_task_exam(df, question_number='2.5', map_answers=['P', 'M', 'R', 'F', 'P'])
#rename column score to score_2_5
result2_5 = result2_5.rename(columns={"score": "score_2_5"})
result2_5.head()

   student_id  score_2_5
0           1          8
1           2          8
2           3        -16
3           4         -3
4           5          8

In [11]:
result2_6 = CBM_score_per_task_exam(df, question_number='2.6', map_answers=['P', 'M', 'P', 'R', 'F'])
#rename column score to score_2_6
result2_6 = result2_6.rename(columns={"score": "score_2_6"})
result2_6.head()

   student_id  score_2_6
0           1         -4
1           2          8
2           3          6
3           4          8
4           5          5

In [12]:
result2_7 = CBM_score_per_task_exam(df, question_number='2.7', map_answers=['P', 'R', 'M', 'P', 'F'])
#rename column score to score_2_7
result2_7 = result2_7.rename(columns={"score": "score_2_7"})
result2_7.head()

   student_id  score_2_7
0           1          6
1           2         -2
2           3         -2
3           4          8
4           5          6

### No minus points

In [13]:
result_no_minus_points_2_1 = CBM_score_per_task_exam_no_minus_points(df, question_number='2.1', map_answers=['F', 'R', 'P', 'M', 'P'])
result_no_minus_points_2_1 = result_no_minus_points_2_1.rename(columns={"score": "score_no_minus_points_2_1"})
result_no_minus_points_2_1.head()

   student_id  score_no_minus_points_2_1
0           1                          7
1           2                          8
2           3                          6
3           4                          8
4           5                          5

In [14]:
result_no_minus_points_2_2 = CBM_score_per_task_exam_no_minus_points(df, question_number='2.2', map_answers=['M', 'R', 'M', 'P', 'F'])
result_no_minus_points_2_2 = result_no_minus_points_2_2.rename(columns={"score": "score_no_minus_points_2_2"})
result_no_minus_points_2_2.head()

   student_id  score_no_minus_points_2_2
0           1                          3
1           2                          8
2           3                          8
3           4                          8
4           5                          4

In [15]:
result_no_minus_points_2_3 = CBM_score_per_task_exam_no_minus_points(df, question_number='2.3', map_answers=['R', 'P', 'M', 'F', 'M'])
result_no_minus_points_2_3 = result_no_minus_points_2_3.rename(columns={"score": "score_no_minus_points_2_3"})
result_no_minus_points_2_3.head()

   student_id  score_no_minus_points_2_3
0           1                          3
1           2                          4
2           3                          4
3           4                          7
4           5                          3

In [16]:
result_no_minus_points_2_4 = CBM_score_per_task_exam_no_minus_points(df, question_number='2.4', map_answers=['R', 'P', 'M', 'F', 'F'])
result_no_minus_points_2_4 = result_no_minus_points_2_4.rename(columns={"score": "score_no_minus_points_2_4"})
result_no_minus_points_2_4.head()

   student_id  score_no_minus_points_2_4
0           1                          0
1           2                          8
2           3                          0
3           4                          8
4           5                          3

In [17]:
result_no_minus_points_2_5 = CBM_score_per_task_exam_no_minus_points(df, question_number='2.5', map_answers=['P', 'M', 'R', 'F', 'P'])
result_no_minus_points_2_5 = result_no_minus_points_2_5.rename(columns={"score": "score_no_minus_points_2_5"})
result_no_minus_points_2_5.head()

   student_id  score_no_minus_points_2_5
0           1                          8
1           2                          8
2           3                          0
3           4                          3
4           5                          8

In [18]:
result_no_minus_points_2_6 = CBM_score_per_task_exam_no_minus_points(df, question_number='2.6', map_answers=['P', 'M', 'P', 'R', 'F'])
result_no_minus_points_2_6 = result_no_minus_points_2_6.rename(columns={"score": "score_no_minus_points_2_6"})
result_no_minus_points_2_6.head()

   student_id  score_no_minus_points_2_6
0           1                          2
1           2                          8
2           3                          6
3           4                          8
4           5                          5

In [19]:
result_no_minus_points_2_7 = CBM_score_per_task_exam_no_minus_points(df, question_number='2.7', map_answers=['P', 'R', 'M', 'P', 'F'])
result_no_minus_points_2_7 = result_no_minus_points_2_7.rename(columns={"score": "score_no_minus_points_2_7"})
result_no_minus_points_2_7.head()

   student_id  score_no_minus_points_2_7
0           1                          6
1           2                          4
2           3                          4
3           4                          8
4           5                          6

In [20]:
#Create a table with all the scores for each question, merge on student_id
overview_table = result2_1.merge(result2_2, on='student_id', how='outer') \
    .merge(result2_3, on='student_id', how='outer') \
    .merge(result2_4, on='student_id', how='outer') \
    .merge(result2_5, on='student_id', how='outer') \
    .merge(result2_6, on='student_id', how='outer') \
    .merge(result2_7, on='student_id', how='outer') 
#Add new column with the total score for each student
overview_table['total_CBM_score_with_minus_points'] = overview_table[['score_2_1', 'score_2_2', 'score_2_3', 'score_2_4', 'score_2_5', 'score_2_6', 'score_2_7']].sum(axis=1)
overview_table = overview_table.drop(columns=['score_2_1', 'score_2_2', 'score_2_3', 'score_2_4', 'score_2_5', 'score_2_6', 'score_2_7'])

overview_table = overview_table.merge(result_no_minus_points_2_1, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_2, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_3, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_4, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_5, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_6, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_7, on='student_id', how='outer') 
#Add new column with the total score for each student
overview_table['total_CBM_score_without_minus_points'] = overview_table[['score_no_minus_points_2_1', 'score_no_minus_points_2_2', 'score_no_minus_points_2_3', 'score_no_minus_points_2_4', 'score_no_minus_points_2_5', 'score_no_minus_points_2_6', 'score_no_minus_points_2_7']].sum(axis=1)
overview_table = overview_table.drop(columns=['score_no_minus_points_2_1', 'score_no_minus_points_2_2', 'score_no_minus_points_2_3', 'score_no_minus_points_2_4', 'score_no_minus_points_2_5', 'score_no_minus_points_2_6', 'score_no_minus_points_2_7'])

overview_table = overview_table.merge(df[['student_id', 'total_score']], on='student_id', how='left')
overview_table = overview_table.drop_duplicates(subset=['student_id'])
# max auto score for tasks 2.1-2.7 is 14 (2 points per task), so max total score without these tasks is 100-14=86
overview_table = overview_table.rename(columns={"total_score": "total_exam_score_without_CBM_out_of_86_points"})
print('Max exam score without CBM tasks is 86')

Max exam score without CBM tasks is 86

In [21]:
overview_table.head()

,student_id,total_CBM_score_with_minus_points,total_CBM_score_without_minus_points,total_exam_score_without_CBM_out_of_86_points
0,1,11.0,29.0,30.01
35,2,36.0,48.0,34.52
70,3,-10.0,28.0,40.48
104,4,44.0,50.0,58.17
139,5,18.0,34.0,48.81

In [22]:
output_folder = root_path / "analysis" / "CBM" / "2025" / "Exam" / "data" / "results"
save_excel_file(overview_table, "IN1020_2025_CBM_exam_results_big_overview", output_folder)

✅ DataFrame saved as: /Users/yulis/Desktop/Masteroppgave_Eksamensanalyse/analysis/CBM/2025/Exam/data/results/IN1020_2025_CBM_exam_results_big_overview.xlsx