In [ ]:
import pandas as pd
import sys
from pathlib import Path

root_path = next((p for p in [Path.cwd(), *Path.cwd().parents] if (p / "utils").exists()), None)
if root_path is None:
    raise FileNotFoundError("Could not locate project root containing 'utils' directory")
sys.path.append(str(root_path))

from utils.helpers import compare_columns

## Here I explore IN1020 2024, IN1020 2023 and IN2120 2024 datasets to understand how to setup a CONFIG-file

### IN1020 2024

In [2]:
df_in1020_2024 = pd.read_csv('../data/csv_files/IN1020_2024_anon.csv')
df_in1020_2024 = df_in1020_2024.rename(columns={"Anonymisert kand.nr": "Anonymisert_kandnr"})
df_in1020_2024.head()

,Column1.result.sourcedId,Column1.result.ext_inspera_userAssessmentSetupId,Column1.result.ext_inspera_userAssessmentId,Column1.result.dateLastModified,Column1.result.ext_inspera_startTime,Column1.result.ext_inspera_endTime,Column1.result.ext_inspera_extraTimeMins,Column1.result.ext_inspera_incidentTimeMins,Kjønn,Anonymisert_kandnr,...,Column1.result.ext_inspera_questions.ext_inspera_questionContentItemId,Column1.result.ext_inspera_questions.ext_inspera_questionNumber,Column1.result.ext_inspera_questions.ext_inspera_questionTitle,Column1.result.ext_inspera_questions.ext_inspera_questionWeight,Column1.result.ext_inspera_questions.ext_inspera_durationSeconds,Column1.result.ext_inspera_questions.ext_inspera_autoScore,Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_inspera_,Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_insper.1,Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_insper.2,Column1.result.score
0,39719815,46609915,34764844,2024-12-11T15:57:52Z,2024-12-11T14:00:02Z,2024-12-11T15:57:52Z,0,0,M,418,...,267129466,1.1,Tallsystemer,1,85,2.4,simpleChoice_1368096164456,Heksadesimale tall,2,71.61
1,39719815,46609915,34764844,2024-12-11T15:57:52Z,2024-12-11T14:00:02Z,2024-12-11T15:57:52Z,0,0,M,418,...,267129466,1.1,Tallsystemer,1,85,2.4,simpleChoice_IA172399520449584402464-f255-46e6...,Oktale tall,7,71.61
2,39719815,46609915,34764844,2024-12-11T15:57:52Z,2024-12-11T14:00:02Z,2024-12-11T15:57:52Z,0,0,M,418,...,267129466,1.1,Tallsystemer,1,85,2.4,simpleChoice_IA17239952044953d28e157-ac4c-49db...,Titallsystemet,8,71.61
3,39719815,46609915,34764844,2024-12-11T15:57:52Z,2024-12-11T14:00:02Z,2024-12-11T15:57:52Z,0,0,M,418,...,267129466,1.1,Tallsystemer,1,85,2.4,simpleChoice_IA1723995204495960f601e-73d5-48f8...,Heksadesimale tall,6,71.61
4,39719815,46609915,34764844,2024-12-11T15:57:52Z,2024-12-11T14:00:02Z,2024-12-11T15:57:52Z,0,0,M,418,...,267129466,1.1,Tallsystemer,1,85,2.4,simpleChoice_IA17239952636882cb13f25-bd73-4352...,Titallsystemet,12,71.61

In [3]:
df_in1020_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65880 entries, 0 to 65879
Data columns (total 28 columns):
 #   Column                                                                            Non-Null Count  Dtype
---  ------                                                                            --------------  -----
 0   Column1.result.sourcedId                                                          65880 non-null  int64
 1   Column1.result.ext_inspera_userAssessmentSetupId                                  65880 non-null  int64
 2   Column1.result.ext_inspera_userAssessmentId                                       65880 non-null  int64
 3   Column1.result.dateLastModified                                                   65880 non-null  object
 4   Column1.result.ext_inspera_startTime                                              65880 non-null  object
 5   Column1.result.ext_inspera_endTime                                                65880 non-null  object
 6   Column1.result.ext_inspera_extraTimeMins                                          65880 non-null  int64
 7   Column1.result.ext_inspera_incidentTimeMins                                       65880 non-null  int64
 8   Kjønn                                                                             65880 non-null  object
 9   Anonymisert_kandnr                                                                65880 non-null  int64
 10  Column1.result.ext_inspera_attendance                                             65880 non-null  bool
 11  Column1.result.lineItem.sourcedId                                                 65880 non-null  int64
 12  Column1.result.lineItem.type                                                      65880 non-null  object
 13  Column1.result.student.sourcedId                                                  65880 non-null  int64
 14  Column1.result.student.type                                                       65880 non-null  object
 15  Column1.result.ext_inspera_autoScore                                              65880 non-null  float64
 16  Column1.result.ext_inspera_questions.ext_inspera_maxQuestionScore                 65880 non-null  float64
 17  Column1.result.ext_inspera_questions.ext_inspera_questionId                       65880 non-null  int64
 18  Column1.result.ext_inspera_questions.ext_inspera_questionContentItemId            65880 non-null  int64
 19  Column1.result.ext_inspera_questions.ext_inspera_questionNumber                   65880 non-null  float64
 20  Column1.result.ext_inspera_questions.ext_inspera_questionTitle                    65880 non-null  object
 21  Column1.result.ext_inspera_questions.ext_inspera_questionWeight                   65880 non-null  int64
 22  Column1.result.ext_inspera_questions.ext_inspera_durationSeconds                  65880 non-null  int64
 23  Column1.result.ext_inspera_questions.ext_inspera_autoScore                        65880 non-null  float64
 24  Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_inspera_  65561 non-null  object
 25  Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_insper.1  29282 non-null  object
 26  Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_insper.2  48239 non-null  object
 27  Column1.result.score                                                              65880 non-null  float64
dtypes: bool(1), float64(5), int64(12), object(10)
memory usage: 13.6+ MB

In [4]:
compare_columns(df_in1020_2024, 'Column1.result.dateLastModified', 'Column1.result.ext_inspera_endTime' )

the rows are identical

In [5]:
compare_columns(df_in1020_2024, 'Column1.result.ext_inspera_autoScore', 'Column1.result.score' )

the rows are identical

### IN1020 2023

In [ ]:
# df_in1020_2023 = pd.read_csv('../data/csv_files/IN1020_2023_anon.csv')
# df_in1020_2023 = df_in1020_2023.rename(columns={"Anonymisert kand.nr": "Anonymisert_kandnr"})
# df_in1020_2023.head()

,Column1.result.sourcedId,Column1.result.ext_inspera_userAssessmentSetupId,Column1.result.ext_inspera_userAssessmentId,Column1.result.dateLastModified,Column1.result.ext_inspera_startTime,Column1.result.ext_inspera_endTime,Column1.result.ext_inspera_extraTimeMins,Column1.result.ext_inspera_incidentTimeMins,Kjønn,Anonymisert_kandnr,...,Column1.result.ext_inspera_questions.ext_inspera_maxQuestionScore,Column1.result.ext_inspera_questions.ext_inspera_questionId,Column1.result.ext_inspera_questions.ext_inspera_questionContentItemId,Column1.result.ext_inspera_questions.ext_inspera_questionNumber,Column1.result.ext_inspera_questions.ext_inspera_questionTitle,Column1.result.ext_inspera_questions.ext_inspera_questionWeight,Column1.result.ext_inspera_questions.ext_inspera_durationSeconds,Column1.result.ext_inspera_questions.ext_inspera_autoScore,Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_inspera_,Column1.result.score
0,24499445,28048982,18845779,2023-12-11T11:54:57Z,2023-12-11T08:00:12Z,2023-12-11T11:54:57Z,0,0,F,329,...,4.5,187896995,185850970,1.1,Dataformater,1,641,4.5,gapImg__9164195750 associableHotspot__146705536,63.0
1,24499445,28048982,18845779,2023-12-11T11:54:57Z,2023-12-11T08:00:12Z,2023-12-11T11:54:57Z,0,0,F,329,...,4.5,187896995,185850970,1.1,Dataformater,1,641,4.5,gapImg_IA1701156824392d16c8498-010d-48e2-8773-...,63.0
2,24499445,28048982,18845779,2023-12-11T11:54:57Z,2023-12-11T08:00:12Z,2023-12-11T11:54:57Z,0,0,F,329,...,4.5,187896995,185850970,1.1,Dataformater,1,641,4.5,gapImg__361670718761 associableHotspot45546867419,63.0
3,24499445,28048982,18845779,2023-12-11T11:54:57Z,2023-12-11T08:00:12Z,2023-12-11T11:54:57Z,0,0,F,329,...,4.5,187896995,185850970,1.1,Dataformater,1,641,4.5,gapImg_IA1701156731070520d3d02-90c1-49b6-b58e-...,63.0
4,24499445,28048982,18845779,2023-12-11T11:54:57Z,2023-12-11T08:00:12Z,2023-12-11T11:54:57Z,0,0,F,329,...,4.5,187896995,185850970,1.1,Dataformater,1,641,4.5,gapImg_IA1701156329933eb2abd04-c1f3-401f-847a-...,63.0

In [ ]:
# df_in1020_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64809 entries, 0 to 64808
Data columns (total 26 columns):
 #   Column                                                                            Non-Null Count  Dtype
---  ------                                                                            --------------  -----
 0   Column1.result.sourcedId                                                          64809 non-null  int64
 1   Column1.result.ext_inspera_userAssessmentSetupId                                  64809 non-null  int64
 2   Column1.result.ext_inspera_userAssessmentId                                       64809 non-null  int64
 3   Column1.result.dateLastModified                                                   64809 non-null  object
 4   Column1.result.ext_inspera_startTime                                              64809 non-null  object
 5   Column1.result.ext_inspera_endTime                                                64809 non-null  object
 6   Column1.result.ext_inspera_extraTimeMins                                          64809 non-null  int64
 7   Column1.result.ext_inspera_incidentTimeMins                                       64809 non-null  int64
 8   Kjønn                                                                             64809 non-null  object
 9   Anonymisert_kandnr                                                                64809 non-null  int64
 10  Column1.result.ext_inspera_attendance                                             64809 non-null  bool
 11  Column1.result.lineItem.sourcedId                                                 64809 non-null  int64
 12  Column1.result.lineItem.type                                                      64809 non-null  object
 13  Column1.result.student.sourcedId                                                  64809 non-null  int64
 14  Column1.result.student.type                                                       64809 non-null  object
 15  Column1.result.ext_inspera_autoScore                                              64809 non-null  float64
 16  Column1.result.ext_inspera_questions.ext_inspera_maxQuestionScore                 64809 non-null  float64
 17  Column1.result.ext_inspera_questions.ext_inspera_questionId                       64809 non-null  int64
 18  Column1.result.ext_inspera_questions.ext_inspera_questionContentItemId            64809 non-null  int64
 19  Column1.result.ext_inspera_questions.ext_inspera_questionNumber                   64809 non-null  float64
 20  Column1.result.ext_inspera_questions.ext_inspera_questionTitle                    64809 non-null  object
 21  Column1.result.ext_inspera_questions.ext_inspera_questionWeight                   64809 non-null  int64
 22  Column1.result.ext_inspera_questions.ext_inspera_durationSeconds                  64809 non-null  int64
 23  Column1.result.ext_inspera_questions.ext_inspera_autoScore                        64809 non-null  float64
 24  Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_inspera_  63436 non-null  object
 25  Column1.result.score                                                              64809 non-null  float64
dtypes: bool(1), float64(5), int64(12), object(8)
memory usage: 12.4+ MB

In [ ]:
# compare_columns(df_in1020_2023, 'Column1.result.dateLastModified', 'Column1.result.ext_inspera_endTime' )

the rows are identical

In [ ]:
# compare_columns(df_in1020_2023, 'Column1.result.ext_inspera_autoScore', 'Column1.result.score' )

the rows are identical

### IN2120 2024

In [ ]:
# df_in2120_2024 = pd.read_csv('../data/csv_files/IN2120_2024_anon.csv')
# df_in2120_2024 = df_in2120_2024.rename(columns={"Anonymisert kand.nr": "Anonymisert_kandnr"})
# df_in2120_2024.head()

,Column1.result.sourcedId,Column1.result.ext_inspera_userAssessmentSetupId,Column1.result.ext_inspera_userAssessmentId,Column1.result.dateLastModified,Column1.result.ext_inspera_startTime,Column1.result.ext_inspera_endTime,Column1.result.ext_inspera_extraTimeMins,Column1.result.ext_inspera_incidentTimeMins,Kjønn,Anonymisert_kandnr,...,Column1.result.ext_inspera_questions.ext_inspera_questionContentItemId,Column1.result.ext_inspera_questions.ext_inspera_questionNumber,Column1.result.ext_inspera_questions.ext_inspera_questionTitle,Column1.result.ext_inspera_questions.ext_inspera_questionWeight,Column1.result.ext_inspera_questions.ext_inspera_durationSeconds,Column1.result.ext_inspera_questions.ext_inspera_autoScore,Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_inspera_,Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_insper.1,Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_insper.2,Column1.result.score
0,38711558,45414139,33694472,2024-11-25T10:29:42Z,2024-11-25T08:00:01Z,2024-11-25T10:29:42Z,0,0,M,77,...,293016054,1.1,Generelle sikkerhetsmålsettinger,1,53,3.0,simpleChoice_1370871167225,konfidensialitet,1,67.5
1,38711558,45414139,33694472,2024-11-25T10:29:42Z,2024-11-25T08:00:01Z,2024-11-25T10:29:42Z,0,0,M,77,...,293016054,1.1,Generelle sikkerhetsmålsettinger,1,53,3.0,simpleChoice_IA17313295674742d674d25-c722-4a92...,tilgjengelighet,6,67.5
2,38711558,45414139,33694472,2024-11-25T10:29:42Z,2024-11-25T08:00:01Z,2024-11-25T10:29:42Z,0,0,M,77,...,293016054,1.1,Generelle sikkerhetsmålsettinger,1,53,3.0,simpleChoice_IA173132962912484243f1a-833f-47fb...,integritet,8,67.5
3,38711558,45414139,33694472,2024-11-25T10:29:42Z,2024-11-25T08:00:01Z,2024-11-25T10:29:42Z,0,0,M,77,...,291712201,1.2,Oversettelse,1,30,2.0,simpleAssociableChoice_IA173100234618194d062e4...,NaN,4 4,67.5
4,38711558,45414139,33694472,2024-11-25T10:29:42Z,2024-11-25T08:00:01Z,2024-11-25T10:29:42Z,0,0,M,77,...,291712201,1.2,Oversettelse,1,30,2.0,simpleAssociableChoice_1373281683440 simpleAss...,NaN,2 2,67.5

In [ ]:
# df_in2120_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47565 entries, 0 to 47564
Data columns (total 30 columns):
 #   Column                                                                            Non-Null Count  Dtype
---  ------                                                                            --------------  -----
 0   Column1.result.sourcedId                                                          47565 non-null  int64
 1   Column1.result.ext_inspera_userAssessmentSetupId                                  47565 non-null  int64
 2   Column1.result.ext_inspera_userAssessmentId                                       47565 non-null  int64
 3   Column1.result.dateLastModified                                                   47565 non-null  object
 4   Column1.result.ext_inspera_startTime                                              47565 non-null  object
 5   Column1.result.ext_inspera_endTime                                                47565 non-null  object
 6   Column1.result.ext_inspera_extraTimeMins                                          47565 non-null  int64
 7   Column1.result.ext_inspera_incidentTimeMins                                       47565 non-null  int64
 8   Kjønn                                                                             47565 non-null  object
 9   Anonymisert_kandnr                                                                47565 non-null  int64
 10  Column1.result.ext_inspera_attendance                                             47565 non-null  bool
 11  Column1.result.lineItem.sourcedId                                                 47565 non-null  int64
 12  Column1.result.lineItem.type                                                      47565 non-null  object
 13  Column1.result.student.sourcedId                                                  47565 non-null  int64
 14  Column1.result.student.type                                                       47565 non-null  object
 15  Column1.result.ext_inspera_finalGradeDate                                         47565 non-null  object
 16  Column1.result.ext_inspera_finalGrade                                             47565 non-null  object
 17  Column1.result.ext_inspera_autoScore                                              47565 non-null  float64
 18  Column1.result.ext_inspera_questions.ext_inspera_maxQuestionScore                 47565 non-null  int64
 19  Column1.result.ext_inspera_questions.ext_inspera_questionId                       47565 non-null  int64
 20  Column1.result.ext_inspera_questions.ext_inspera_questionContentItemId            47565 non-null  int64
 21  Column1.result.ext_inspera_questions.ext_inspera_questionNumber                   47565 non-null  float64
 22  Column1.result.ext_inspera_questions.ext_inspera_questionTitle                    47565 non-null  object
 23  Column1.result.ext_inspera_questions.ext_inspera_questionWeight                   47565 non-null  int64
 24  Column1.result.ext_inspera_questions.ext_inspera_durationSeconds                  47565 non-null  int64
 25  Column1.result.ext_inspera_questions.ext_inspera_autoScore                        47565 non-null  float64
 26  Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_inspera_  46719 non-null  object
 27  Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_insper.1  15768 non-null  object
 28  Column1.result.ext_inspera_questions.ext_inspera_candidateResponses.ext_insper.2  27852 non-null  object
 29  Column1.result.score                                                              47565 non-null  float64
dtypes: bool(1), float64(4), int64(13), object(12)
memory usage: 10.6+ MB

In [ ]:
# compare_columns(df_in2120_2024, 'Column1.result.dateLastModified', 'Column1.result.ext_inspera_endTime' )

the rows are identical

In [ ]:
# compare_columns(df_in2120_2024, 'Column1.result.ext_inspera_autoScore', 'Column1.result.score' )

the rows are identical