In [1]:
from pathlib import Path
import sys
import pandas as pd
import yaml

root_path = next((p for p in [Path.cwd(), *Path.cwd().parents] if (p / "utils").exists()), None)
if root_path is None:
    raise FileNotFoundError("Could not locate project root containing 'utils' directory")
sys.path.append(str(root_path))

from utils.helpers import save_csv_file, load_data

In [2]:
df = load_data("../data/cleaned_data/IN1020_2025konte_cleaned_data.csv")
df.head()

Data loaded successfully from ../data/cleaned_data/IN1020_2025konte_cleaned_data.csv

,exam_start_time,exam_end_time,extra_time_mins,incident_time_mins,student_id,max_question_score,question_number,question_title,question_duration_sec,auto_score_per_question,candidate_response_code,candidate_response_text,response_CBM,total_score
0,2026-01-22 14:01:25,2026-01-22 15:33:03,0,0,5,2.0,1.1,IN1020 K-H25 bit-representasjon,225,2.0,simpleChoice_1368096164456,-85,2,68.25
1,2026-01-22 14:01:25,2026-01-22 15:33:03,0,0,5,2.0,1.1,IN1020 K-H25 bit-representasjon,225,2.0,simpleChoice_1368096164453,171,1,68.25
2,2026-01-22 14:01:25,2026-01-22 15:33:03,0,0,5,3.5,1.2,IN1020 K-H25 Tallsystemer representasjon,97,3.0,simpleChoice_1368096164456,cafebabe,2,68.25
3,2026-01-22 14:01:25,2026-01-22 15:33:03,0,0,5,3.5,1.2,IN1020 K-H25 Tallsystemer representasjon,97,3.0,simpleChoice_IA17639200973561dd93152-292d-4b6b...,123hh321,4,68.25
4,2026-01-22 14:01:25,2026-01-22 15:33:03,0,0,5,3.5,1.2,IN1020 K-H25 Tallsystemer representasjon,97,3.0,simpleChoice_1368096164453,0f0cdb0d,1,68.25

In [3]:
df['question_number'] = df['question_number'].astype(str)
valid_questions = [f"2.{i}" for i in range(1, 16)]
df_CBM = df[df['question_number'].isin(valid_questions)]
df_CBM.head()

,exam_start_time,exam_end_time,extra_time_mins,incident_time_mins,student_id,max_question_score,question_number,question_title,question_duration_sec,auto_score_per_question,candidate_response_code,candidate_response_text,response_CBM,total_score
21,2026-01-22 14:01:25,2026-01-22 15:33:03,0,0,5,1.0,2.1,H25K - CBA - PC,32,1.0,simpleAssociableChoice_1373281683439 simpleAss...,simpleAssociableChoice_1373281683439 simpleAss...,1 5,68.25
22,2026-01-22 14:01:25,2026-01-22 15:33:03,0,0,5,1.0,2.1,H25K - CBA - PC,32,1.0,simpleAssociableChoice_IA1764163304079c22e31fb...,simpleAssociableChoice_IA1764163304079c22e31fb...,4 1,68.25
23,2026-01-22 14:01:25,2026-01-22 15:33:03,0,0,5,1.0,2.1,H25K - CBA - PC,32,1.0,simpleAssociableChoice_IA1764163295493078f6095...,simpleAssociableChoice_IA1764163295493078f6095...,3 1,68.25
24,2026-01-22 14:01:25,2026-01-22 15:33:03,0,0,5,1.0,2.1,H25K - CBA - PC,32,1.0,simpleAssociableChoice_IA1764163311627e7d4bd50...,simpleAssociableChoice_IA1764163311627e7d4bd50...,5 1,68.25
25,2026-01-22 14:01:25,2026-01-22 15:33:03,0,0,5,1.0,2.1,H25K - CBA - PC,32,1.0,simpleAssociableChoice_1373281683440 simpleAss...,simpleAssociableChoice_1373281683440 simpleAss...,2 1,68.25