In [1]:
from pathlib import Path
import sys

root_path = next((p for p in [Path.cwd(), *Path.cwd().parents] if (p / "utils").exists()), None)
if root_path is None:
    raise FileNotFoundError("Could not locate project root containing 'utils' directory")
sys.path.append(str(root_path))

from utils.helpers import load_data, save_excel_file
from utils.CBM_score_per_task import CBM_score_per_task_konte

In [2]:
df = load_data("../data/CBM_format/IN1020_2025konte_CBM.csv")
df = df[['student_id', 'question_number', 'answer_alternative', 'confidence_level', 'auto_score', 'total_score']]
df.head()

Data loaded successfully from ../data/CBM_format/IN1020_2025konte_CBM.csv

,student_id,question_number,answer_alternative,confidence_level,auto_score,total_score
0,38,2.1,1,100.0,20.0,68.25
1,38,2.1,4,0.0,20.0,68.25
2,38,2.1,3,0.0,20.0,68.25
3,38,2.1,5,0.0,20.0,68.25
4,38,2.1,2,0.0,20.0,68.25

In [3]:
result2_1 = CBM_score_per_task_konte(df, question_number='2.1', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_1
result2_1 = result2_1.rename(columns={"score": "score_2_1"})
result2_1.head()

   student_id  score_2_1
0           1          8
1           2          8
2           3          4
3           4          8
4           5          8

In [4]:
result2_2 = CBM_score_per_task_konte(df, question_number='2.2', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_2
result2_2 = result2_2.rename(columns={"score": "score_2_2"})
result2_2.head()

   student_id  score_2_2
0           1          8
1           2          4
2           3          8
3           4          6
4           5          4

In [5]:
result2_3 = CBM_score_per_task_konte(df, question_number='2.3', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_3
result2_3 = result2_3.rename(columns={"score": "score_2_3"})
result2_3.head()

   student_id  score_2_3
0           1          8
1           2        -16
2           3          4
3           4          8
4           5          8

In [6]:
result2_4 = CBM_score_per_task_konte(df, question_number='2.4', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_4
result2_4 = result2_4.rename(columns={"score": "score_2_4"})
result2_4.head()

   student_id  score_2_4
0           1          8
1           2          8
2           3          8
3           4          8
4           5          8

In [7]:
result2_5 = CBM_score_per_task_konte(df, question_number='2.5', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_5
result2_5 = result2_5.rename(columns={"score": "score_2_5"})
result2_5.head()

   student_id  score_2_5
0           1          8
1           2        -16
2           4          8
3           5          4
4           6          8

In [8]:
result2_6 = CBM_score_per_task_konte(df, question_number='2.6', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_6
result2_6 = result2_6.rename(columns={"score": "score_2_6"})
result2_6.head()

   student_id  score_2_6
0           1          8
1           2          8
2           3          8
3           4          8
4           5          8

In [9]:
result2_7 = CBM_score_per_task_konte(df, question_number='2.7', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_7
result2_7 = result2_7.rename(columns={"score": "score_2_7"})
result2_7.head()

   student_id  score_2_7
0           1          5
1           2          8
2           3          8
3           4          7
4           5        -12

In [10]:
result2_8 = CBM_score_per_task_konte(df, question_number='2.8', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_8
result2_8 = result2_8.rename(columns={"score": "score_2_8"})
result2_8.head()

   student_id  score_2_8
0           1          0
1           2          4
2           4          8
3           5          8
4           6          6

In [11]:
result2_9 = CBM_score_per_task_konte(df, question_number='2.9', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_9
result2_9 = result2_9.rename(columns={"score": "score_2_9"})
result2_9.head()

   student_id  score_2_9
0           1          4
1           2          4
2           4          8
3           5          8
4           6          8

In [12]:
result2_10 = CBM_score_per_task_konte(df, question_number='2.10', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_10
result2_10 = result2_10.rename(columns={"score": "score_2_10"})
result2_10.head()

   student_id  score_2_10
0           1           8
1           2           8
2           4           8
3           5           8
4           6           6

In [13]:
result2_11 = CBM_score_per_task_konte(df, question_number='2.11', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_11
result2_11 = result2_11.rename(columns={"score": "score_2_11"})
result2_11.head()

   student_id  score_2_11
0           1           8
1           2           8
2           4           8
3           5           8
4           6           8

In [14]:
result2_12 = CBM_score_per_task_konte(df, question_number='2.12', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_12
result2_12 = result2_12.rename(columns={"score": "score_2_12"})
result2_12.head()

   student_id  score_2_12
0           1          -2
1           2           8
2           3           8
3           4           6
4           6          -2

In [15]:
result2_13 = CBM_score_per_task_konte(df, question_number='2.13', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_13
result2_13 = result2_13.rename(columns={"score": "score_2_13"})
result2_13.head()

   student_id  score_2_13
0           1           4
1           2           8
2           4           8
3           5           4
4           6           8

In [16]:
result2_14 = CBM_score_per_task_konte(df, question_number='2.14', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_14
result2_14 = result2_14.rename(columns={"score": "score_2_14"})
result2_14.head()

   student_id  score_2_14
0           1           6
1           2         -16
2           3           8
3           4           8
4           5           8

In [17]:
result2_15 = CBM_score_per_task_konte(df, question_number='2.15', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_15
result2_15 = result2_15.rename(columns={"score": "score_2_15"})
result2_15.head()

   student_id  score_2_15
0           1           8
1           2           8
2           4           8
3           5           8
4           6           8

In [18]:
#Create a table with all the scores for each question, merge on student_id
overview_table = result2_1.merge(result2_2, on='student_id', how='outer') \
    .merge(result2_3, on='student_id', how='outer') \
    .merge(result2_4, on='student_id', how='outer') \
    .merge(result2_5, on='student_id', how='outer') \
    .merge(result2_6, on='student_id', how='outer') \
    .merge(result2_7, on='student_id', how='outer') \
    .merge(result2_8, on='student_id', how='outer') \
    .merge(result2_9, on='student_id', how='outer') \
    .merge(result2_10, on='student_id', how='outer') \
    .merge(result2_11, on='student_id', how='outer') \
    .merge(result2_12, on='student_id', how='outer') \
    .merge(result2_13, on='student_id', how='outer') \
    .merge(result2_14, on='student_id', how='outer') \
    .merge(result2_15, on='student_id', how='outer')
#Add new column with the total score for each student
overview_table['total_CBM_score'] = overview_table[['score_2_1', 'score_2_2', 'score_2_3', 'score_2_4', 'score_2_5', 'score_2_6', 'score_2_7', 'score_2_8', 'score_2_9', 'score_2_10', 'score_2_11', 'score_2_12', 'score_2_13', 'score_2_14', 'score_2_15']].sum(axis=1)
# Add 'invalid_answer' in cells where score is NaN
overview_table = overview_table.fillna('invalid_answer')
overview_table.head()

,student_id,score_2_1,score_2_2,score_2_3,score_2_4,score_2_5,score_2_6,score_2_7,score_2_8,score_2_9,score_2_10,score_2_11,score_2_12,score_2_13,score_2_14,score_2_15,total_CBM_score
0,1,8.0,8.0,8.0,8,8.0,8.0,5.0,0.0,4.0,8.0,8.0,-2.0,4.0,6.0,8.0,89.0
1,2,8.0,4.0,-16.0,8,-16.0,8.0,8.0,4.0,4.0,8.0,8.0,8.0,8.0,-16.0,8.0,36.0
2,3,4.0,8.0,4.0,8,invalid_answer,8.0,8.0,invalid_answer,invalid_answer,invalid_answer,invalid_answer,8.0,invalid_answer,8.0,invalid_answer,56.0
3,4,8.0,6.0,8.0,8,8.0,8.0,7.0,8.0,8.0,8.0,8.0,6.0,8.0,8.0,8.0,115.0
4,5,8.0,4.0,8.0,8,4.0,8.0,-12.0,8.0,8.0,8.0,8.0,invalid_answer,4.0,8.0,8.0,80.0

In [19]:
output_folder = root_path / "analysis" / "CBM" / "2025" / "Konte" / "data" / "CBM_format"
save_excel_file(overview_table, "IN1020_2025_CBM_konte_results", output_folder)

✅ DataFrame saved as: /Users/yulis/Desktop/Masteroppgave_Eksamensanalyse/analysis/CBM/2025/Konte/data/CBM_format/IN1020_2025_CBM_konte_results.xlsx