In [90]:
from pathlib import Path
import sys

root_path = next((p for p in [Path.cwd(), *Path.cwd().parents] if (p / "utils").exists()), None)
if root_path is None:
    raise FileNotFoundError("Could not locate project root containing 'utils' directory")
sys.path.append(str(root_path))

from utils.helpers import load_data, save_excel_file
from utils.CBM_score_per_task import CBM_score_per_task_konte_no_F, CBM_score_per_task_konte_no_minus_points

In [91]:
df = load_data("../data/CBM_format/IN1020_2025konte_CBM.csv")
df = df[['student_id', 'question_number', 'auto_score_per_question', 'answer_alternative', 'confidence_level', 'auto_score', 'total_score']]
df['total_score'] = df['total_score']-df['auto_score']
df.sort_values(by=['student_id', 'question_number', 'answer_alternative'], inplace=True)
df.head()

Data loaded successfully from ../data/CBM_format/IN1020_2025konte_CBM.csv

,student_id,question_number,auto_score_per_question,answer_alternative,confidence_level,auto_score,total_score
2431,1,2.1,1.0,1,100.0,20.0,54.25
2434,1,2.1,1.0,2,0.0,20.0,54.25
2433,1,2.1,1.0,3,0.0,20.0,54.25
2430,1,2.1,1.0,4,0.0,20.0,54.25
2432,1,2.1,1.0,5,0.0,20.0,54.25

### With minus points

In [92]:
result2_1 = CBM_score_per_task_konte_no_F(df, question_number='2.1', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_1
result2_1 = result2_1.rename(columns={"score": "score_2_1"})
result2_1.head()

   student_id  score_2_1
0           1          8
1           2          8
2           3          4
3           4          8
4           5          8

In [93]:
result2_2 = CBM_score_per_task_konte_no_F(df, question_number='2.2', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_2
result2_2 = result2_2.rename(columns={"score": "score_2_2"})
result2_2.head()

   student_id  score_2_2
0           1          8
1           2          4
2           3          8
3           4          6
4           5          4

In [94]:
result2_3 = CBM_score_per_task_konte_no_F(df, question_number='2.3', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_3
result2_3 = result2_3.rename(columns={"score": "score_2_3"})
result2_3.head()

   student_id  score_2_3
0           1          8
1           2        -12
2           3          4
3           4          8
4           5          8

In [95]:
result2_4 = CBM_score_per_task_konte_no_F(df, question_number='2.4', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_4
result2_4 = result2_4.rename(columns={"score": "score_2_4"})
result2_4.head()

   student_id  score_2_4
0           1          8
1           2          8
2           3          8
3           4          8
4           5          8

In [96]:
result2_5 = CBM_score_per_task_konte_no_F(df, question_number='2.5', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_5
result2_5 = result2_5.rename(columns={"score": "score_2_5"})
result2_5.head()

   student_id  score_2_5
0           1          8
1           2        -12
2           4          8
3           5          4
4           6          8

In [97]:
result2_6 = CBM_score_per_task_konte_no_F(df, question_number='2.6', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_6
result2_6 = result2_6.rename(columns={"score": "score_2_6"})
result2_6.head()

   student_id  score_2_6
0           1          8
1           2          8
2           3          8
3           4          8
4           5          8

In [98]:
result2_7 = CBM_score_per_task_konte_no_F(df, question_number='2.7', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_7
result2_7 = result2_7.rename(columns={"score": "score_2_7"})
result2_7.head()

   student_id  score_2_7
0           1          5
1           2          8
2           3          8
3           4          7
4           5        -12

In [99]:
result2_8 = CBM_score_per_task_konte_no_F(df, question_number='2.8', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_8
result2_8 = result2_8.rename(columns={"score": "score_2_8"})
result2_8.head()

   student_id  score_2_8
0           1          0
1           2          4
2           4          8
3           5          8
4           6          6

In [100]:
result2_9 = CBM_score_per_task_konte_no_F(df, question_number='2.9', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_9
result2_9 = result2_9.rename(columns={"score": "score_2_9"})
result2_9.head()

   student_id  score_2_9
0           1          4
1           2          4
2           4          8
3           5          8
4           6          8

In [101]:
result2_10 = CBM_score_per_task_konte_no_F(df, question_number='2.10', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_10
result2_10 = result2_10.rename(columns={"score": "score_2_10"})
result2_10.head()

   student_id  score_2_10
0           1           8
1           2           8
2           4           8
3           5           8
4           6           6

In [102]:
result2_11 = CBM_score_per_task_konte_no_F(df, question_number='2.11', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_11
result2_11 = result2_11.rename(columns={"score": "score_2_11"})
result2_11.head()

   student_id  score_2_11
0           1           8
1           2           8
2           4           8
3           5           8
4           6           8

In [103]:
result2_12 = CBM_score_per_task_konte_no_F(df, question_number='2.12', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_12
result2_12 = result2_12.rename(columns={"score": "score_2_12"})
result2_12.head()

   student_id  score_2_12
0           1           0
1           2           8
2           3           8
3           4           6
4           6           0

In [104]:
result2_13 = CBM_score_per_task_konte_no_F(df, question_number='2.13', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_13
result2_13 = result2_13.rename(columns={"score": "score_2_13"})
result2_13.head()

   student_id  score_2_13
0           1           4
1           2           8
2           4           8
3           5           4
4           6           8

In [105]:
result2_14 = CBM_score_per_task_konte_no_F(df, question_number='2.14', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_14
result2_14 = result2_14.rename(columns={"score": "score_2_14"})
result2_14.head()

   student_id  score_2_14
0           1           6
1           2         -12
2           3           8
3           4           8
4           5           8

In [106]:
result2_15 = CBM_score_per_task_konte_no_F(df, question_number='2.15', map_answers=['R', 'P', 'P', 'M', 'F'])
#rename column score to score_2_15
result2_15 = result2_15.rename(columns={"score": "score_2_15"})
result2_15.head()

   student_id  score_2_15
0           1           8
1           2           8
2           4           8
3           5           8
4           6           8

### No minus points

In [107]:
result_no_minus_points_2_1 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.1', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_1 = result_no_minus_points_2_1.rename(columns={"score": "score_no_minus_points_2_1"})
result_no_minus_points_2_1.head()

   student_id  score_no_minus_points_2_1
0           1                          8
1           2                          8
2           3                          4
3           4                          8
4           5                          8

In [108]:
result_no_minus_points_2_2 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.2', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_2 = result_no_minus_points_2_2.rename(columns={"score": "score_no_minus_points_2_2"})
result_no_minus_points_2_2.head()

   student_id  score_no_minus_points_2_2
0           1                          8
1           2                          4
2           3                          8
3           4                          6
4           5                          4

In [109]:
result_no_minus_points_2_3 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.3', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_3 = result_no_minus_points_2_3.rename(columns={"score": "score_no_minus_points_2_3"})
result_no_minus_points_2_3.head()

   student_id  score_no_minus_points_2_3
0           1                          8
1           2                          0
2           3                          4
3           4                          8
4           5                          8

In [110]:
result_no_minus_points_2_4 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.4', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_4 = result_no_minus_points_2_4.rename(columns={"score": "score_no_minus_points_2_4"})
result_no_minus_points_2_4.head()

   student_id  score_no_minus_points_2_4
0           1                          8
1           2                          8
2           3                          8
3           4                          8
4           5                          8

In [111]:
result_no_minus_points_2_5 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.5', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_5 = result_no_minus_points_2_5.rename(columns={"score": "score_no_minus_points_2_5"})
result_no_minus_points_2_5.head()

   student_id  score_no_minus_points_2_5
0           1                          8
1           2                          0
2           4                          8
3           5                          4
4           6                          8

In [112]:
result_no_minus_points_2_6 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.6', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_6 = result_no_minus_points_2_6.rename(columns={"score": "score_no_minus_points_2_6"})
result_no_minus_points_2_6.head()

   student_id  score_no_minus_points_2_6
0           1                          8
1           2                          8
2           3                          8
3           4                          8
4           5                          8

In [113]:
result_no_minus_points_2_7 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.7', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_7 = result_no_minus_points_2_7.rename(columns={"score": "score_no_minus_points_2_7"})
result_no_minus_points_2_7.head()

   student_id  score_no_minus_points_2_7
0           1                          5
1           2                          8
2           3                          8
3           4                          7
4           5                          0

In [114]:
result_no_minus_points_2_8 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.8', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_8 = result_no_minus_points_2_8.rename(columns={"score": "score_no_minus_points_2_8"})
result_no_minus_points_2_8.head()

   student_id  score_no_minus_points_2_8
0           1                          4
1           2                          4
2           4                          8
3           5                          8
4           6                          6

In [115]:
result_no_minus_points_2_9 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.9', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_9 = result_no_minus_points_2_9.rename(columns={"score": "score_no_minus_points_2_9"})
result_no_minus_points_2_9.head()

   student_id  score_no_minus_points_2_9
0           1                          4
1           2                          4
2           4                          8
3           5                          8
4           6                          8

In [116]:
result_no_minus_points_2_10 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.10', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_10 = result_no_minus_points_2_10.rename(columns={"score": "score_no_minus_points_2_10"})
result_no_minus_points_2_10.head()

   student_id  score_no_minus_points_2_10
0           1                           8
1           2                           8
2           4                           8
3           5                           8
4           6                           6

In [117]:
result_no_minus_points_2_11 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.11', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_11 = result_no_minus_points_2_11.rename(columns={"score": "score_no_minus_points_2_11"})
result_no_minus_points_2_11.head()

   student_id  score_no_minus_points_2_11
0           1                           8
1           2                           8
2           4                           8
3           5                           8
4           6                           8

In [118]:
result_no_minus_points_2_12 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.12', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_12 = result_no_minus_points_2_12.rename(columns={"score": "score_no_minus_points_2_12"})
result_no_minus_points_2_12.head()

   student_id  score_no_minus_points_2_12
0           1                           4
1           2                           8
2           3                           8
3           4                           6
4           6                           4

In [119]:
result_no_minus_points_2_13 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.13', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_13 = result_no_minus_points_2_13.rename(columns={"score": "score_no_minus_points_2_13"})
result_no_minus_points_2_13.head()

   student_id  score_no_minus_points_2_13
0           1                           4
1           2                           8
2           4                           8
3           5                           4
4           6                           8

In [120]:
result_no_minus_points_2_14 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.14', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_14 = result_no_minus_points_2_14.rename(columns={"score": "score_no_minus_points_2_14"})
result_no_minus_points_2_14.head()

   student_id  score_no_minus_points_2_14
0           1                           6
1           2                           0
2           3                           8
3           4                           8
4           5                           8

In [121]:
result_no_minus_points_2_15 = CBM_score_per_task_konte_no_minus_points(df, question_number='2.15', map_answers=['R', 'P', 'P', 'M', 'F'])
result_no_minus_points_2_15 = result_no_minus_points_2_15.rename(columns={"score": "score_no_minus_points_2_15"})
result_no_minus_points_2_15.head()

   student_id  score_no_minus_points_2_15
0           1                           8
1           2                           8
2           4                           8
3           5                           8
4           6                           8

In [124]:
#Create a table with all the scores for each question, merge on student_id
overview_table = result2_1.merge(result2_2, on='student_id', how='outer') \
    .merge(result2_3, on='student_id', how='outer') \
    .merge(result2_4, on='student_id', how='outer') \
    .merge(result2_5, on='student_id', how='outer') \
    .merge(result2_6, on='student_id', how='outer') \
    .merge(result2_7, on='student_id', how='outer') \
    .merge(result2_8, on='student_id', how='outer') \
    .merge(result2_9, on='student_id', how='outer') \
    .merge(result2_10, on='student_id', how='outer') \
    .merge(result2_11, on='student_id', how='outer') \
    .merge(result2_12, on='student_id', how='outer') \
    .merge(result2_13, on='student_id', how='outer') \
    .merge(result2_14, on='student_id', how='outer') \
    .merge(result2_15, on='student_id', how='outer')
#Add new column with the total score for each student
overview_table['total_CBM_score_with_minus_points'] = overview_table[['score_2_1', 'score_2_2', 'score_2_3', 'score_2_4', 'score_2_5', 'score_2_6', 'score_2_7', 'score_2_8', 'score_2_9', 'score_2_10', 'score_2_11', 'score_2_12', 'score_2_13', 'score_2_14', 'score_2_15']].sum(axis=1)
overview_table = overview_table.drop(columns=['score_2_1', 'score_2_2', 'score_2_3', 'score_2_4', 'score_2_5', 'score_2_6', 'score_2_7', 'score_2_8', 'score_2_9', 'score_2_10', 'score_2_11', 'score_2_12', 'score_2_13', 'score_2_14', 'score_2_15'])

overview_table = overview_table.merge(result_no_minus_points_2_1, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_2, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_3, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_4, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_5, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_6, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_7, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_8, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_9, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_10, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_11, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_12, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_13, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_14, on='student_id', how='outer') \
    .merge(result_no_minus_points_2_15, on='student_id', how='outer')
#Add new column with the total score for each student
overview_table['total_CBM_score_without_minus_points'] = overview_table[['score_no_minus_points_2_1', 'score_no_minus_points_2_2', 'score_no_minus_points_2_3', 'score_no_minus_points_2_4', 'score_no_minus_points_2_5', 'score_no_minus_points_2_6', 'score_no_minus_points_2_7', 'score_no_minus_points_2_8', 'score_no_minus_points_2_9', 'score_no_minus_points_2_10', 'score_no_minus_points_2_11', 'score_no_minus_points_2_12', 'score_no_minus_points_2_13', 'score_no_minus_points_2_14', 'score_no_minus_points_2_15']].sum(axis=1)
overview_table = overview_table.drop(columns=['score_no_minus_points_2_1', 'score_no_minus_points_2_2', 'score_no_minus_points_2_3', 'score_no_minus_points_2_4', 'score_no_minus_points_2_5', 'score_no_minus_points_2_6', 'score_no_minus_points_2_7', 'score_no_minus_points_2_8', 'score_no_minus_points_2_9', 'score_no_minus_points_2_10', 'score_no_minus_points_2_11', 'score_no_minus_points_2_12', 'score_no_minus_points_2_13', 'score_no_minus_points_2_14', 'score_no_minus_points_2_15'])

overview_table = overview_table.merge(df[['student_id', 'total_score']], on='student_id', how='left')
overview_table = overview_table.drop_duplicates(subset=['student_id'])
overview_table = overview_table.rename(columns={"total_score": "total_exam_score_without_CBM_out_of_80_points"})
print('Max exam score without CBM tasks is 80')

Max exam score without CBM tasks is 80

In [125]:
overview_table.head()

,student_id,total_CBM_score_with_minus_points,total_CBM_score_without_minus_points,total_exam_score_without_CBM_out_of_80_points
0,1,91.0,99.0,54.25
75,2,48.0,84.0,28.34
150,3,56.0,56.0,27.62
190,4,115.0,115.0,64.00
265,5,80.0,92.0,37.75

In [126]:
output_folder = root_path / "analysis" / "CBM" / "2025" / "Konte" / "data" / "results"
save_excel_file(overview_table, "IN1020_2025_CBM_konte_results_big_overview", output_folder)

✅ DataFrame saved as: /Users/yulis/Desktop/Masteroppgave_Eksamensanalyse/analysis/CBM/2025/Konte/data/results/IN1020_2025_CBM_konte_results_big_overview.xlsx